**Google Drive Baglantisi**


In [37]:
#Google Drive baglanti
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [38]:
%cd gdrive/My Drive/Colab Notebooks/Artificial Neural Network/
%ls

[Errno 2] No such file or directory: 'gdrive/My Drive/Colab Notebooks/Artificial Neural Network/'
/content/gdrive/My Drive/Colab Notebooks/Artificial Neural Network
ANN_keras.ipynb                   ANN_scikit.ipynb  diabetes.csv
ANN_keras-Train-Test-Final.ipynb  AyriClass.csv     Final_Veriseti.csv
ANN_keras-Train-Test.ipynb        deneme.h5         Numara_AdSoyad.docx


**Verileri Oluştur**

In [39]:
#Gereken kutuphaneler yuklenmeli
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split  #Rastgele Train Test Bolmek icin
from sklearn.preprocessing import MinMaxScaler        #Min-Max normalization yapmak icin
import numpy

numpy.random.seed(7)
#veriseti yukleme
dataset=numpy.loadtxt("Final_Veriseti.csv", delimiter=",")

#datalar 0:16 arasi featurelar alindi
datalar=dataset[:,0:16]
datalar=MinMaxScaler().fit_transform(datalar)
#Veriler [0 1] araligina normalize edildi

etiketler=dataset[:,16]
#etiketler 16.indis class (outcome) alindi
etiketler=np_utils.to_categorical(etiketler, 7)
# Class isimleri 0,1,2,3,...6 iken 7 giris icin ayarlandi 
# 1= [1,0,0,0,0,0,0], 2=[0,1,0,0,0,0,0], ...

# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(datalar, etiketler, test_size=0.2, random_state=0)
#X_train: Train Datalari
#X_test:  Test Dataları
#Y_train: Train Etiketleri
#Y_test:  Test Etiketleri

In [43]:
print(etiketler.shape)
print(etiketler[13600,:])
#print(datalar.shape)
#print(datalar)

(13611, 7)
[0. 0. 0. 0. 0. 0. 1.]


**MLP Yapisi Kurulumu**

In [73]:
model=Sequential()
#8 feature girisli oldugu icin input_dim=16 secildi
model.add(Dense(25, input_dim=16, activation='sigmoid')) # Hidden Layer 1 (25 noron)
#hidden layer 2 ye input_dim yazilmaz.
model.add(Dense(100, activation='tanh'))              # Hidden Layer 2  (100 noron)
#Cikis 7 adet oldugu icin oldugu icin Dense 7 output noron baglandi
model.add(Dense(7, activation='softmax'))            #Output Layer
#activation=sigmoid, relu, linear, tanh, softmax

#Modeli Derleme
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#loss=KLD, mae, mse, mean_squared_error, cosine_proximity, binary_crossentropy, poisson, categorical_crossentropy
#optimizer: adam, RMSprop, SGD

#batch_size: Egitim sirasinda verisetinden ornekler kacar kacar alinacak
model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=1)
#verbose=0 -> Eğitimi adim adim gostermez sadece son epoch getirir
basarim=model.evaluate(X_train, Y_train)

print("\n Train %s : %.2f%% " % (model.metrics_names[1], basarim[1]*100))


Epoch 1/50
1089/1089 [==============================] - 2s 1ms/step - loss: 1.4858 - accuracy: 0.4186
Epoch 2/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3812 - accuracy: 0.8747
Epoch 3/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.3327 - accuracy: 0.8790
Epoch 4/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3199 - accuracy: 0.8780
Epoch 5/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3105 - accuracy: 0.8822
Epoch 6/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3003 - accuracy: 0.8940
Epoch 7/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.2772 - accuracy: 0.8949
Epoch 8/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.2786 - accuracy: 0.8944
Epoch 9/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.2673 - accuracy: 0.8994
Epoch 10/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.255

In [59]:
model.summary()
#model.get_config()
#from keras.utils.vis_utils import plot_model
#plot_model(model, to_file='model.png')

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 25)                425       
_________________________________________________________________
dense_13 (Dense)             (None, 100)               2600      
_________________________________________________________________
dense_14 (Dense)             (None, 7)                 707       
Total params: 3,732
Trainable params: 3,732
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.save("deneme.h5")

**Confusion Matrix**

In [88]:
from sklearn.metrics import classification_report,confusion_matrix

_, test_acc = model.evaluate(X_test, Y_test, verbose=0)
print('>Test Accuracy: %.2f%%' % (test_acc * 100.0))


#yPredicted = model.predict(X_test)           #Direk cikista alinan degerleri verir
#yPredicted = model.predict_proba(X_test)     #Olasiliksal olarak cikti verir
yPredicted = model.predict_classes(X_test)
Y_Test_actual=numpy.argmax(Y_test,axis=1)

print(classification_report(y_true=Y_Test_actual, y_pred=yPredicted))
print(confusion_matrix(y_true=Y_Test_actual, y_pred=yPredicted))


>Test Accuracy: 91.52%
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       376
           1       0.97      0.80      0.88       255
           2       1.00      1.00      1.00        92
           3       0.91      0.95      0.93       350
           4       0.93      0.96      0.95       390
           5       0.84      0.87      0.85       525
           6       0.92      0.93      0.93       735

    accuracy                           0.92      2723
   macro avg       0.93      0.92      0.92      2723
weighted avg       0.92      0.92      0.92      2723

[[345   2   0   0   0  22   7]
 [  3 204   0  25   2  21   0]
 [  0   0  92   0   0   0   0]
 [  1   4   0 333   9   3   0]
 [  0   0   0   8 376   5   1]
 [  2   1   0   1  12 455  54]
 [  6   0   0   0   4  38 687]]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
