<a href="https://colab.research.google.com/github/alialtinok/AI/blob/main/HT_Sensor_Butunleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
 #Google Drive Baglantisi
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [17]:
%cd /content/gdrive/My Drive/Colab Notebooks

/content/gdrive/My Drive/Colab Notebooks


In [18]:
%ls

 2020-2021_Lisans_Final_MLP/   HT_Sensor_Butunleme.csv    'Yapay Zeka'/
'Artificial Neural Network'/   HT_Sensor_Butunleme.ipynb
 diabetes.csv                  Numara_AdSoyad.docx


In [76]:
#MLP Yapısını kurma (Gereken Kutuphaneleri cagiralim)
from keras.models import Sequential  
from keras.layers import Dense
from sklearn import preprocessing
import numpy
from keras.utils import np_utils
numpy.random.seed(7)

dataset = numpy.loadtxt("HT_Sensor_Butunleme.csv", delimiter=",")

datalar = dataset[:,0:10]
datalar = preprocessing.normalize(datalar)

# : tum satırlar, 0:8 arasi sutunlar (feature)
etiketler = dataset[:,10]
etiketler=np_utils.to_categorical(etiketler, 3)
# : tum satırlar, 8.sutun arasi (class)


model = Sequential()
#input_dim=0 cunku 10 feature var
model.add(Dense(100, input_dim=10, activation='linear')) #Hidden layer1
model.add(Dense(140, activation='elu'))              #Hidden layer2
model.add(Dense(220, activation='relu'))              #Hidden layer2
model.add(Dense(3, activation='softplus'))            #Output layer (kac cikis varsa o kadar noron)
#activation=sigmoid, relu, linear, tanh,Elu, softmax, swish softplus, softmax,


model.compile(loss='poisson', optimizer='adam', metrics=['accuracy'])
#loss=mse, mae, mean_squared_error, cosine_proximity, binary_crossentropy, poisson, KLD
# Modeli verilere gore train etme (Fitting)
model.fit(datalar, etiketler, epochs=300, batch_size=10 )
basarim=model.evaluate(datalar,etiketler)
print("\n %s: %.2f%% " % (model.metrics_names[1], basarim[1]*100)) 

Epoch 1/300
143/143 [==============================] - 1s 3ms/step - loss: 0.6452 - accuracy: 0.6019
Epoch 2/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5454 - accuracy: 0.7388
Epoch 3/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5397 - accuracy: 0.7638
Epoch 4/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5380 - accuracy: 0.7744
Epoch 5/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5341 - accuracy: 0.7538
Epoch 6/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5241 - accuracy: 0.7573
Epoch 7/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5215 - accuracy: 0.7670
Epoch 8/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5117 - accuracy: 0.7937
Epoch 9/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5135 - accuracy: 0.7804
Epoch 10/300
143/143 [==============================] - 0s 3ms/step - loss: 0.5091 - accura

In [71]:
print(datalar)
print(etiketler)

[[-0.19041332 -0.21337293  0.29526442 ...  0.39025343 -0.36178697
  -0.30831313]
 [-0.22943047 -0.23104616  0.35732603 ...  0.38660647 -0.35831887
  -0.34781579]
 [-0.23179527 -0.18302215  0.38408834 ...  0.33837434 -0.36201216
  -0.30850504]
 ...
 [-0.34628056  0.08828078 -0.35100249 ...  0.3219039   0.07173899
  -0.46198287]
 [-0.22749431 -0.34720289  0.18465101 ...  0.39838911 -0.55176234
  -0.08855087]
 [-0.13421947 -0.38552879 -0.62422117 ...  0.08722225 -0.44324982
  -0.00441086]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [72]:
model.summary()

Model: "sequential_45"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_212 (Dense)            (None, 100)               1100      
_________________________________________________________________
dense_213 (Dense)            (None, 150)               15150     
_________________________________________________________________
dense_214 (Dense)            (None, 250)               37750     
_________________________________________________________________
dense_215 (Dense)            (None, 3)                 753       
Total params: 54,753
Trainable params: 54,753
Non-trainable params: 0
_________________________________________________________________


In [74]:
model.save("100.h5")

In [ ]:
#Localde çalisacaklar icin yuklenmesi gereken kutuphaneler
#pip yukleme (pip install)
# pip install numpy scipy
# pip install scikit-learn
# pip install pillow
# pip install h5py
# pip install keras,  pip install -q keras