**Google Drive Baglantisi**


In [1]:
#Google Drive baglanti
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd gdrive/My Drive/Colab Notebooks/Artificial Neural Network/
%ls

/content/gdrive/My Drive/Colab Notebooks/Artificial Neural Network
ANN_keras.ipynb                                    deneme.h5
ANN_keras-Train-Test-Final-FeatureSelection.ipynb  diabetes.csv
ANN_keras-Train-Test-Final.ipynb                   Final_Veriseti.csv
ANN_keras-Train-Test.ipynb                         Numara_AdSoyad.docx
ANN_scikit.ipynb


**Verileri Oluştur**

In [3]:
#Gereken kutuphaneler yuklenmeli
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split  #Rastgele Train Test Bolmek icin
from sklearn.preprocessing import MinMaxScaler        #Min-Max normalization yapmak icin
import numpy

numpy.random.seed(7)
#veriseti yukleme
dataset=numpy.loadtxt("Final_Veriseti.csv", delimiter=",")

#datalar 0:16 arasi featurelar alindi
datalar=dataset[:,0:16]
datalar=MinMaxScaler().fit_transform(datalar)
#Veriler [0 1] araligina normalize edildi

etiketler=dataset[:,16]
#etiketler 16.indis class (outcome) alindi
etiketler=np_utils.to_categorical(etiketler, 7)
# Class isimleri 0,1,2,3,...6 iken 7 cikis icin ayarlandi 
# 0= [1,0,0,0,0,0,0], 1=[0,1,0,0,0,0,0], 2=[0,0,1,0,0,0,0] ...

# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(datalar, etiketler, test_size=0.2, random_state=0)
#X_train: Train Datalari
#X_test:  Test Dataları
#Y_train: Train Etiketleri
#Y_test:  Test Etiketleri

In [4]:
print(etiketler.shape)
print(etiketler[13600,:])
#print(datalar.shape)
#print(datalar)

(13611, 7)
[0. 0. 0. 0. 0. 0. 1.]


In [5]:
#Sequential Feature Selection
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier

sfs = SequentialFeatureSelector(estimator=KNeighborsClassifier(n_neighbors=3),
                    k_features=5, #Kac feature secilecek
                    forward=True, #İleri yonlu ise true, geri yonlu ise false
                    floating=False,
                    scoring='accuracy') #cv=1
X_new=sfs.fit_transform(X_train, Y_train)
print(X_train.shape)
print(X_new.shape)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


(10888, 16)
(10888, 5)


In [6]:
print(sfs.subsets_[5])
#'feature_idx' icerisindeki featurelar secilen featurelar

{'feature_idx': (1, 10, 12, 13, 15), 'cv_scores': array([0.91414141, 0.90312213, 0.91781451, 0.90996785, 0.91134589]), 'avg_score': 0.911278357551377, 'feature_names': ('1', '10', '12', '13', '15')}


In [7]:
#PCA: Principle Component Analysis
from sklearn.decomposition import PCA

pca = PCA(n_components=10) #n_components: Kac feature a donusturulecek
fit = pca.fit(X_train)
X_train_new = fit.transform(X_train)
X_test_new =fit.transform(X_test)
# summarize components
#print("Explained Variance: %s" % fit.explained_variance_ratio_)
#print(fit.components_)

print(X_train.shape)
print(X_train_new.shape)

(10888, 16)
(10888, 10)


**MLP Yapisi Kurulumu**

In [ ]:
model=Sequential()
#8 feature girisli oldugu icin input_dim=16 secildi
model.add(Dense(25, input_dim=16, activation='sigmoid')) # Hidden Layer 1 (25 noron)
#hidden layer 2 ye input_dim yazilmaz.
model.add(Dense(100, activation='tanh'))              # Hidden Layer 2  (100 noron)
#Cikis 7 adet oldugu icin oldugu icin Dense 7 output noron baglandi
model.add(Dense(7, activation='softmax'))            #Output Layer
#activation=sigmoid, relu, linear, tanh, softmax

#Modeli Derleme
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#loss=KLD, mae, mse, mean_squared_error, cosine_proximity, binary_crossentropy, poisson, categorical_crossentropy
#optimizer: adam, RMSprop, SGD

#batch_size: Egitim sirasinda verisetinden ornekler kacar kacar alinacak
model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=1)
#verbose=0 -> Eğitimi adim adim gostermez sadece son epoch getirir
basarim=model.evaluate(X_train, Y_train)

print("\n Train %s : %.2f%% " % (model.metrics_names[1], basarim[1]*100))


Epoch 1/50
1089/1089 [==============================] - 2s 1ms/step - loss: 1.4858 - accuracy: 0.4186
Epoch 2/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3812 - accuracy: 0.8747
Epoch 3/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.3327 - accuracy: 0.8790
Epoch 4/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3199 - accuracy: 0.8780
Epoch 5/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3105 - accuracy: 0.8822
Epoch 6/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.3003 - accuracy: 0.8940
Epoch 7/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.2772 - accuracy: 0.8949
Epoch 8/50
1089/1089 [==============================] - 2s 1ms/step - loss: 0.2786 - accuracy: 0.8944
Epoch 9/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.2673 - accuracy: 0.8994
Epoch 10/50
1089/1089 [==============================] - 1s 1ms/step - loss: 0.255

In [ ]:
model.summary()
#model.get_config()
#from keras.utils.vis_utils import plot_model
#plot_model(model, to_file='model.png')

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 25)                425       
_________________________________________________________________
dense_13 (Dense)             (None, 100)               2600      
_________________________________________________________________
dense_14 (Dense)             (None, 7)                 707       
Total params: 3,732
Trainable params: 3,732
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.save("deneme.h5")

**Confusion Matrix**

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

_, test_acc = model.evaluate(X_test, Y_test, verbose=0)
print('>Test Accuracy: %.2f%%' % (test_acc * 100.0))


#yPredicted = model.predict(X_test)           #Direk cikista alinan degerleri verir
#yPredicted = model.predict_proba(X_test)     #Olasiliksal olarak cikti verir
yPredicted = model.predict_classes(X_test)
Y_Test_actual=numpy.argmax(Y_test,axis=1)

print(classification_report(y_true=Y_Test_actual, y_pred=yPredicted))
print(confusion_matrix(y_true=Y_Test_actual, y_pred=yPredicted))


>Test Accuracy: 91.52%
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       376
           1       0.97      0.80      0.88       255
           2       1.00      1.00      1.00        92
           3       0.91      0.95      0.93       350
           4       0.93      0.96      0.95       390
           5       0.84      0.87      0.85       525
           6       0.92      0.93      0.93       735

    accuracy                           0.92      2723
   macro avg       0.93      0.92      0.92      2723
weighted avg       0.92      0.92      0.92      2723

[[345   2   0   0   0  22   7]
 [  3 204   0  25   2  21   0]
 [  0   0  92   0   0   0   0]
 [  1   4   0 333   9   3   0]
 [  0   0   0   8 376   5   1]
 [  2   1   0   1  12 455  54]
 [  6   0   0   0   4  38 687]]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
