In [1]:
 #Google Drive Baglantisi
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
%cd /content/gdrive/My Drive/Colab Notebooks

/content/gdrive/My Drive/Colab Notebooks


In [4]:
%ls

 100.h5                        diabetes.csv
 2020-2021_Lisans_Final_MLP/   diyabet.ipynb
 99.51.h5                      HT_Sensor_Butunleme.csv
 99.93.h5                      HT_Sensor_Butunleme.ipynb
'Artificial Neural Network'/   Numara_AdSoyad.docx


In [15]:
#MLP Yapısını kurma (Gereken Kutuphaneleri cagiralim)
from keras.models import Sequential  
from keras.layers import Dense
from sklearn import preprocessing
import numpy
numpy.random.seed(7)

dataset = numpy.loadtxt("diabetes.csv", delimiter=",")

datalar = dataset[:,0:8]
datalar = preprocessing.normalize(datalar)

# : tum satırlar, 0:8 arasi sutunlar (feature)
etiketler = dataset[:,8]
# : tum satırlar, 8.sutun arasi (class)


model = Sequential()
#input_dim=0 cunku 10 feature var
model.add(Dense(100, input_dim=8, activation='relu')) #Hidden layer1
model.add(Dense(140, activation='relu'))              #Hidden layer2
model.add(Dense(220, activation='tanh'))              #Hidden layer2
model.add(Dense(240, activation='relu'))              #Hidden layer2
model.add(Dense(1, activation='sigmoid'))            #Output layer (kac cikis varsa o kadar noron)
#activation=sigmoid, relu, linear, tanh,Elu, softmax, swish softplus, softmax,


model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
#loss=mse, mae, mean_squared_error, cosine_proximity, binary_crossentropy, poisson, KLD
# Modeli verilere gore train etme (Fitting)
model.fit(datalar, etiketler, epochs=470, batch_size=10 )
basarim=model.evaluate(datalar,etiketler)
print("\n %s: %.2f%% " % (model.metrics_names[1], basarim[1]*100)) 

Epoch 1/470
77/77 [==============================] - 1s 2ms/step - loss: 0.2293 - accuracy: 0.6269
Epoch 2/470
77/77 [==============================] - 0s 2ms/step - loss: 0.2168 - accuracy: 0.6521
Epoch 3/470
77/77 [==============================] - 0s 2ms/step - loss: 0.2136 - accuracy: 0.6506
Epoch 4/470
77/77 [==============================] - 0s 2ms/step - loss: 0.2129 - accuracy: 0.6505
Epoch 5/470
77/77 [==============================] - 0s 2ms/step - loss: 0.2114 - accuracy: 0.6821
Epoch 6/470
77/77 [==============================] - 0s 2ms/step - loss: 0.1967 - accuracy: 0.6763
Epoch 7/470
77/77 [==============================] - 0s 2ms/step - loss: 0.1950 - accuracy: 0.6946
Epoch 8/470
77/77 [==============================] - 0s 2ms/step - loss: 0.1987 - accuracy: 0.6958
Epoch 9/470
77/77 [==============================] - 0s 2ms/step - loss: 0.2020 - accuracy: 0.6768
Epoch 10/470
77/77 [==============================] - 0s 2ms/step - loss: 0.1996 - accuracy: 0.7033
Epoch 11/

In [12]:
print(datalar)
print(etiketler)

[[0.03355237 0.82762513 0.40262844 ... 0.18789327 0.00350622 0.27960308]
 [0.008424   0.71604034 0.55598426 ... 0.22407851 0.00295683 0.26114412]
 [0.04039768 0.92409698 0.32318146 ... 0.11765825 0.00339341 0.16159073]
 ...
 [0.02691539 0.65135243 0.38758161 ... 0.14103664 0.00131885 0.16149234]
 [0.00665306 0.83828547 0.39918356 ... 0.20025708 0.00232192 0.31269379]
 [0.00791454 0.73605211 0.55401772 ... 0.24060198 0.00249308 0.18203439]]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0.

In [13]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_29 (Dense)             (None, 100)               900       
_________________________________________________________________
dense_30 (Dense)             (None, 140)               14140     
_________________________________________________________________
dense_31 (Dense)             (None, 220)               31020     
_________________________________________________________________
dense_32 (Dense)             (None, 220)               48620     
_________________________________________________________________
dense_33 (Dense)             (None, 1)                 221       
Total params: 94,901
Trainable params: 94,901
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.save("deneme_95.05.h5")

In [ ]:
#Localde çalisacaklar icin yuklenmesi gereken kutuphaneler
#pip yukleme (pip install)
# pip install numpy scipy
# pip install scikit-learn
# pip install pillow
# pip install h5py
# pip install keras,  pip install -q keras